import type { SeasonData } from '../../engine';

/**
 * Lazy access to the committed season files. Each JSON becomes its own
 * chunk, fetched on demand — the app never bundles all 12 seasons up front.
 */
const modules = import.meta.glob<SeasonData>('../../data/seasons/*.json', {
  import: 'default',
});

export const availableSeasons: number[] = Object.keys(modules)
  .map((path) => Number(/(\d+)\.json$/.exec(path)![1]))
  .sort((a, b) => a - b);

/** Demo seasons generated by `npm run demo-data` live far in the future. */
export const isDemoSeason = (year: number): boolean => year >= 2090;

/**
 * Load `target` plus up to `burnIn` seasons before it, oldest first.
 * Years with no committed file are silently skipped, so a 2014 target
 * with burn-in 3 simply starts at 2014.
 */
export async function loadSeasonRange(target: number, burnIn: number): Promise<SeasonData[]> {
  const years: number[] = [];
  for (let year = target - burnIn; year <= target; year++) {
    if (availableSeasons.includes(year)) years.push(year);
  }
  return Promise.all(years.map((year) => modules[`../../data/seasons/${year}.json`]!()));
}
